# The Cholesky decomposition

In [2]:
import numba
import numpy as np
from numba import njit
from scipy.linalg import cholesky
np.set_printoptions(suppress=True, precision=4, linewidth=150)

In [3]:
xvals = np.linspace(-3, 3, 100)

Let ${\bf \Sigma}$ be an $N\,P\times N\,P$ positive definite matrix such that
$$
{\bf \Sigma} =
\begin{bmatrix}
    {\bf \sigma}_{1,1} & {\bf \sigma}_{1,2} & \cdots & {\bf \sigma}_{1,N}\\
    {\bf \sigma}_{2,1} & {\bf \sigma}_{2,2} & \cdots & {\bf \sigma}_{2,N}\\
    \vdots & \vdots & \ddots & \vdots \\
    {\bf \sigma}_{N,1} & {\bf \sigma}_{N,2} & \ldots & {\bf \sigma}_{N,N}
\end{bmatrix}
$$

We seek to decompose ${\bf \Sigma} = {\bf L\,R\,L}^\intercal$
with ${\bf R} = {\rm diag}(R_1, \ldots, R_N)$ and
${\bf L} = \{L_{i,j} : i \in \{1, \ldots N\}, j \leq i\}$ a block-lower triangular matrix with $L_{i,i} = {\bf I}$

We seek ${\bf L}$ and ${\bf R}$ such that
$$
    ({\bf L\,R\,L}^\intercal)_{i,j} = \sigma_{i,j}
$$

The choleskly decomposition yields the following algorithm

$$
\begin{aligned}
    {\bf R}_i &= \sigma_{i,i} - \sum_{k=1}^{i-1}{\bf L}_{i,k}\,{\bf R}_{k}\,{\bf L}_{i,k}^\intercal
    &\text{for }i=1,\ldots,T\\
    {\bf L}_{j,i} &= \left[\sigma_{j,i} - \sum_{k=1}^{j-1}{\bf L}_{j,k}\,{\bf R}_k\,{\bf L}_{i,k}^\intercal\right]\,{\bf R}^{-1}_i
    &\text{for } i=2,\ldots,T\text{ and }\, j<i
\end{aligned}
$$

In [4]:
np.random.seed(314)
d = 10
S = np.random.randn(d, d)
S = S @ S.T

In [5]:
LR = np.linalg.cholesky(S)

In [6]:
S

array([[ 5.0561, -2.1211, -4.9336,  1.7228, -1.1385, -4.5112,  4.1296,  1.4875, -1.6306,  1.1243],
       [-2.1211, 10.6464,  4.9359, -4.3093, -0.2017, -1.0459, -0.481 ,  3.6758, -3.9953,  1.0951],
       [-4.9336,  4.9359, 15.9405, -1.533 ,  3.0908,  3.4337, -2.9025, -0.8334, -1.8779, -1.783 ],
       [ 1.7228, -4.3093, -1.533 ,  7.1912,  0.5188, -0.0115, -0.6576, -3.4788, -1.2517,  2.3797],
       [-1.1385, -0.2017,  3.0908,  0.5188,  7.163 ,  1.5606, -2.7542,  0.1679,  1.2635,  1.2001],
       [-4.5112, -1.0459,  3.4337, -0.0115,  1.5606,  5.6308, -4.7271, -2.4139,  3.0437, -1.037 ],
       [ 4.1296, -0.481 , -2.9025, -0.6576, -2.7542, -4.7271,  7.7946,  5.5878, -3.4981, -0.1397],
       [ 1.4875,  3.6758, -0.8334, -3.4788,  0.1679, -2.4139,  5.5878, 11.2912, -1.5058, -0.1032],
       [-1.6306, -3.9953, -1.8779, -1.2517,  1.2635,  3.0437, -3.4981, -1.5058, 11.7888,  0.6448],
       [ 1.1243,  1.0951, -1.783 ,  2.3797,  1.2001, -1.037 , -0.1397, -0.1032,  0.6448,  5.8579]])

In [7]:
LR

array([[ 2.2486,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9433,  3.1236,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-2.1941,  0.9176,  3.2069,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.7662, -1.1482,  0.3747,  2.2683,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.5063, -0.2175,  0.6796,  0.1774,  2.5231,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-2.0063, -0.9407, -0.0327,  0.2018,  0.1295,  0.8138,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.8365,  0.4006,  0.2368, -0.7466, -0.6998, -0.5121,  1.7017,  0.    ,  0.    ,  0.    ],
       [ 0.6615,  1.3766, -0.2012, -1.027 ,  0.4444,  0.4319,  2.1357,  1.7082,  0.    ,  0.    ],
       [-0.7252, -1.4981, -0.6531, -0.9573,  0.4693,  0.357 , -0.949 ,  0.9282,  2.3592,  0.    ],
       [ 0.5   ,  0.5016, -0.3574,  1.1932,  0.6316,  0.1274,  0.1315, -0.3439,  1.174 ,  1.3695]])

In [8]:
R = np.diag(LR)
L = LR / np.diag(LR)

In [9]:
L

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407, -0.3676,  0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252, -0.0696,  0.2119,  0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922, -0.3012, -0.0102,  0.089 ,  0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.1283,  0.0738, -0.3291, -0.2774, -0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.4407, -0.0627, -0.4528,  0.1761,  0.5308,  1.255 ,  1.    ,  0.    ,  0.    ],
       [-0.3225, -0.4796, -0.2036, -0.422 ,  0.186 ,  0.4387, -0.5576,  0.5433,  1.    ,  0.    ],
       [ 0.2224,  0.1606, -0.1115,  0.526 ,  0.2503,  0.1566,  0.0773, -0.2013,  0.4976,  1.    ]])

In [10]:
R

array([2.2486, 3.1236, 3.2069, 2.2683, 2.5231, 0.8138, 1.7017, 1.7082, 2.3592, 1.3695])

## Step-by-step construction

In [11]:
R_vals = np.zeros(d)
L_vals = np.zeros((d,d))

## Step 1 — construction of the first column

In [12]:
R_vals[0] = S[0,0]
R_vals[0]

5.056067919855992

In [13]:
R_vals

array([5.0561, 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ])

In [14]:
L_vals[:, 0] = S[:, 0] / R_vals[0]
L_vals[:, 0]

array([ 1.    , -0.4195, -0.9758,  0.3407, -0.2252, -0.8922,  0.8168,  0.2942, -0.3225,  0.2224])

In [15]:
L_vals

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.3225,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2224,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ]])

## Step 2 — construction of second column

In [16]:
R_vals[1] = S[1,1] - L_vals[1,0] * R_vals[0] * L_vals[1,0]
R_vals[1]

9.756605325989712

In [17]:
L_vals[1:, 1] = (S[1:,1] - L_vals[1:,0] * R_vals[0] * L_vals[1,0]) / R_vals[1]

In [18]:
L_vals

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.2938,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407, -0.3676,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252, -0.0696,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922, -0.3012,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.1283,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.4407,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.3225, -0.4796,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2224,  0.1606,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ]])

## Step 3 — construction of third column

In [19]:
i = 2
R_vals[i] = S[i, i] - (L_vals[i, :i] * R_vals[:i] * L_vals[i, :i]).sum()

In [20]:
R_vals

array([ 5.0561,  9.7566, 10.2844,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ])

In [21]:
R ** 2

array([ 5.0561,  9.7566, 10.2844,  5.1453,  6.366 ,  0.6622,  2.8959,  2.9181,  5.5658,  1.8757])

In [22]:
L_vals[i:, i] = (S[i:,i] - (L_vals[i:, :i] * R_vals[:i] * L_vals[i, :i]).sum(axis=1)) / R_vals[i]
L_vals

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407, -0.3676,  0.1168,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252, -0.0696,  0.2119,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922, -0.3012, -0.0102,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.1283,  0.0738,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.4407, -0.0627,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.3225, -0.4796, -0.2036,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2224,  0.1606, -0.1115,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ]])

In [23]:
L

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407, -0.3676,  0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252, -0.0696,  0.2119,  0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922, -0.3012, -0.0102,  0.089 ,  0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.1283,  0.0738, -0.3291, -0.2774, -0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.4407, -0.0627, -0.4528,  0.1761,  0.5308,  1.255 ,  1.    ,  0.    ,  0.    ],
       [-0.3225, -0.4796, -0.2036, -0.422 ,  0.186 ,  0.4387, -0.5576,  0.5433,  1.    ,  0.    ],
       [ 0.2224,  0.1606, -0.1115,  0.526 ,  0.2503,  0.1566,  0.0773, -0.2013,  0.4976,  1.    ]])

## The cholesky decomposition

$$
\begin{aligned}
    {\bf R}_j &= \sigma_{j,j} - \sum_{k=1}^{j-1}{\bf L}_{j,k}\,{\bf R}_{k}\,{\bf L}_{j,k}^\intercal,
    &\text{for } j=1,\ldots,T\\
    {\bf L}_{i,j} &=
    \left[\sigma_{i,j} - \sum_{k=1}^{j-1}{\bf L}_{i,k}\,{\bf R}_k\,{\bf L}_{j,k}^\intercal\right]\,{\bf R}^{-1}_j,
    &\text{for } j=1,\ldots,T\text{ and }\ i\geq j
\end{aligned}
$$

Note that ${\bf L}_{j,j} = {\bf I}$.

Order of operations:
```
 —  —   —   —   —
|1
|2  6  
|3  7  10
|4  8  11  13
|5  9  12  14  15
```

In [24]:
R_vals = np.zeros(d)
L_vals = np.zeros((d,d))

# Iterate column by column (j)
for j in range(d):
    R_vals[j] = S[j, j] - (L_vals[j, :j] * R_vals[:j] * L_vals[j, :j]).sum()
    L_vals[j:, j] = (S[j:,j] - (L_vals[j:, :j] * R_vals[:j] * L_vals[j, :j]).sum(axis=1)) / R_vals[j]

In [25]:
R_vals

array([ 5.0561,  9.7566, 10.2844,  5.1453,  6.366 ,  0.6622,  2.8959,  2.9181,  5.5658,  1.8757])

In [26]:
R ** 2

array([ 5.0561,  9.7566, 10.2844,  5.1453,  6.366 ,  0.6622,  2.8959,  2.9181,  5.5658,  1.8757])

In [27]:
L_vals

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407, -0.3676,  0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252, -0.0696,  0.2119,  0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922, -0.3012, -0.0102,  0.089 ,  0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.1283,  0.0738, -0.3291, -0.2774, -0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.4407, -0.0627, -0.4528,  0.1761,  0.5308,  1.255 ,  1.    ,  0.    ,  0.    ],
       [-0.3225, -0.4796, -0.2036, -0.422 ,  0.186 ,  0.4387, -0.5576,  0.5433,  1.    ,  0.    ],
       [ 0.2224,  0.1606, -0.1115,  0.526 ,  0.2503,  0.1566,  0.0773, -0.2013,  0.4976,  1.    ]])

In [28]:
L

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.9758,  0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.3407, -0.3676,  0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2252, -0.0696,  0.2119,  0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.8922, -0.3012, -0.0102,  0.089 ,  0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8168,  0.1283,  0.0738, -0.3291, -0.2774, -0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.2942,  0.4407, -0.0627, -0.4528,  0.1761,  0.5308,  1.255 ,  1.    ,  0.    ,  0.    ],
       [-0.3225, -0.4796, -0.2036, -0.422 ,  0.186 ,  0.4387, -0.5576,  0.5433,  1.    ,  0.    ],
       [ 0.2224,  0.1606, -0.1115,  0.526 ,  0.2503,  0.1566,  0.0773, -0.2013,  0.4976,  1.    ]])

## Solving system of linear equations

In [145]:
np.random.seed(314)
b = np.random.randn(d)

In [146]:
@njit
def cholesky_decompose(A):
    d, _ = A.shape

    R_vals = np.zeros(d)
    L_vals = np.zeros((d,d))
    
    # Iterate column by column (j)
    for j in range(d):
        R_vals[j] = A[j, j] - (L_vals[j, :j] * R_vals[:j] * L_vals[j, :j]).sum()
        L_vals[j:, j] = (A[j:,j] - (L_vals[j:, :j] * R_vals[:j] * L_vals[j, :j]).sum(axis=1)) / R_vals[j]

    return L_vals, R_vals

## Solution by cholesky decomposition

$$
\begin{aligned}
    {\bf A}\,{\bf x} &= {\bf b}\\ 
    {\bf L}{\bf R}{\bf L}^\intercal\,{\bf x} &= {\bf b}\\
    {\bf L}{\bf c} &= {\bf b},
\end{aligned}
$$
with ${\bf c} = {\bf R L}^\intercal\,{\bf x}$

---

### Solving for ${\bf c}$
$$
\begin{aligned}
    {\bf c}_1 &= {\bf b}_1,\\
    {\bf c}_k &= {\bf b}_k - \sum_{n=1}^{k-1} {\bf L}_{k,n}\,{\bf c}_n & \text{for } k \geq 2 
\end{aligned}
$$

---

### Solving for ${\bf x}$
$$
\begin{aligned}
    {\bf c} &= {\bf R L}^\intercal\,{\bf x}\\  
    {\bf R}^{-1}\,{\bf c} &= {\bf L}^\intercal {\bf x}.
\end{aligned}
$$
We obtain 

$$
\begin{aligned}
    {\bf x}_T &= {\bf R}_T^{-1}\,{\bf c}_T,\\
    {\bf x}_k &= {\bf R}_k^{-1}\,{\bf c}_k - \sum_{n=k+1}^T{\bf L}_{n,k}^\intercal\,{\bf b}_n
\end{aligned}
$$

In [147]:
L, R = cholesky_decompose(S)

In [148]:
# Foward pass
c_vals = np.zeros(d)
for k in range(d):
    c_vals[k] = b[k] - (L[k, :] * c_vals)[:k].sum()


# Backward pass
x_sol = np.zeros(d)
for k in range(d, 0, -1):
    k = k - 1
    x_sol[k] = c_vals[k] /  R[k] - (L[:, k] * x_sol)[k+1:].sum()

In [149]:
x_sol

array([ 2.2013, -0.0689,  0.3167, -0.8309, -0.4675,  1.8569, -0.434 ,  0.1046, -0.4015,  0.6319])

In [150]:
x_sol_np = np.linalg.solve(S, b)
x_sol_np

array([ 2.2013, -0.0689,  0.3167, -0.8309, -0.4675,  1.8569, -0.434 ,  0.1046, -0.4015,  0.6319])

In [151]:
np.allclose(x_sol, x_sol_np)

True

### Numba implementation

In [279]:
@njit
def cholesky_decompose(A):
    d, _ = A.shape

    R_vals = np.zeros(d)
    L_vals = np.zeros((d,d))
    
    # Iterate column by column (j)
    for j in range(d):
        R_vals[j] = A[j, j] - (L_vals[j, :j] * R_vals[:j] * L_vals[j, :j]).sum()
        L_vals[j:, j] = (A[j:,j] - (L_vals[j:, :j] * R_vals[:j] * L_vals[j, :j]).sum(axis=1)) / R_vals[j]

    return L_vals, R_vals


@njit
def solve_fwd(b, L):
    """
    Forward pass for solving a system of linear equations
    using the cholesky decomposition
    """
    d, _ = L.shape
    c_vals = np.zeros(d)
    for k in range(d):
        c_vals[k] = b[k] - (L[k, :] * c_vals)[:k].sum()

    return c_vals


@njit
def solve_back(c, L, R):
    """
    Backward pass for solving a system of linear equations
    using the cholesky decomposition
    """
    d, _ = L.shape
    x_vals = np.zeros(d)
    for k in range(d, 0, -1):
        k = k - 1
        x_vals[k] = c[k] / R[k] - (L[:, k] * x_vals)[k+1:].sum()
    return x_vals


@njit
def solve1d(A, b):
    L, R = cholesky_decompose(A)
    c = solve_fwd(b, L)
    x = solve_back(c, L, R)
    return x

### Inverting L matrix

In [297]:
ix = 6
imask = np.eye(d)[:, ix]

In [298]:
np.linalg.solve(L, imask)

array([ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  1.    , -1.255 ,  1.2396, -0.9468])

In [299]:
c = solve_fwd(imask, L)
c

array([ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  1.    , -1.255 ,  1.2396, -0.9468])

### All together

In [176]:
solve1d(L, imask)

array([-1.9322, -3.114 , -0.3584, -4.2605,  0.7871,  2.1539,  3.2434, -2.6766, -3.6092,  3.603 ])

### Time comparison

In [170]:
%%timeit -n 100 -r 10
solve1d(S, b)

20 µs ± 4.3 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [171]:
%%timeit -n 100 -r 10
np.linalg.solve(S, b)

8.7 µs ± 1.38 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Generalisation to system of matrix equations
Having the psd matrix ${\bf A}\in\mathbb{R}^{d\times d}$ and matrix ${\bf B}\in\mathbb{R}^{d\times l}$.
We seek ${\bf X}\in{\mathbb R}^{d\times l}$ such that
$$
    {\bf A}{\bf X} = {\bf B}
$$

## Solution by cholesky decomposition

$$
\begin{aligned}
    {\bf A}\,{\bf X} &= {\bf B}\\ 
    {\bf L}{\bf R}{\bf L}^\intercal\,{\bf X} &= {\bf B}\\
    {\bf L}{\bf C} &= {\bf B},
\end{aligned}
$$
with ${\bf C} = {\bf R L}^\intercal\,{\bf X}$

---

### Solving for ${\bf C}$
$$
\begin{aligned}
    {\bf C}_{1,:} &= {\bf B}_{1,:},\\
    {\bf C}_{k,:} &= {\bf B}_k - \sum_{n=1}^{k-1} {\bf L}_{k,n}\,{\bf C}_{n,:} & \text{for } k \geq 2 
\end{aligned}
$$

---

### Solving for ${\bf X}$
$$
\begin{aligned}
    {\bf C} &= {\bf R L}^\intercal\,{\bf x}\\  
    {\bf R}^{-1}\,{\bf C} &= {\bf L}^\intercal {\bf X}.
\end{aligned}
$$
We obtain 

$$
\begin{aligned}
    {\bf X}_{d,:} &= {\bf R}_T^{-1}\,{\bf C}_{d,:},\\
    {\bf X}_{k, :} &= {\bf R}_k^{-1}\,{\bf C}_{k,:} - \sum_{n=k+1}^T{\bf L}_{n,k}^\intercal\,{\bf B}_{n,:}
\end{aligned}
$$

## Example

In [300]:
np.random.seed(314)
B = np.random.randn(d, 5)

### Cholesky approach

#### Forward pass

In [319]:
@njit
def solve_fwd(L, B):
    """
    Forward pass for solving a system of linear equations
    using the cholesky decomposition
    """
    d, m = B.shape
    C_vals = np.zeros((d, m))
    for k in range(d):
        C_vals[k, :] = B[k, :] - (L[k, :, None] * C_vals)[:k].sum(axis=0)

    return C_vals

In [320]:
C = solve_fwd(L, B)
C

array([[ 0.1661,  0.782 ,  0.8523, -0.7071, -0.9317],
       [ 0.9563,  0.1063,  0.7393, -1.0692,  0.4721],
       [-0.4001, -0.2001,  0.1159,  0.3885, -0.8563],
       [-0.277 ,  1.4617,  1.706 ,  0.9847,  1.7104],
       [-1.6556, -0.5248, -0.6755,  2.2711,  0.039 ],
       [ 0.7231,  1.9459,  1.305 , -0.9563, -2.3815],
       [-0.6616, -0.0389,  0.1645, -0.109 , -0.5842],
       [ 1.4478, -1.447 , -0.4717,  0.2963,  1.9067],
       [-1.734 ,  1.287 ,  1.3289, -1.3204,  1.1356],
       [ 1.7133, -0.3745, -2.3745, -0.1133, -1.7759]])

#### Backward pass

In [321]:
@njit
def solve_back(C, L, R):
    """
    Backward pass for solving a system of linear equations
    using the cholesky decomposition.
    Variable "C" is the result of running the forward pass.
    """
    d, m = C.shape
    X_vals = np.zeros((d, m))
    for k in range(d, 0, -1):
        k = k - 1
        X_vals[k] = C[k] / R[k] - (L[:, k, None] * X_vals)[k+1:].sum(axis=0)
    return X_vals

In [322]:
solve_back(C, L, R)

array([[ 0.3687,  3.6485,  2.9531, -1.7842, -3.9627],
       [-1.3636,  1.6662,  2.4564, -0.6197,  0.0223],
       [ 0.4623, -0.112 , -0.3541, -0.0861, -0.3378],
       [-0.9128,  0.2053,  1.1994,  0.219 ,  1.5058],
       [-1.0906,  0.1335,  0.5197,  0.3508,  0.3267],
       [-0.6197,  3.8872,  3.3633, -1.7039, -3.7149],
       [-2.1022,  1.0846,  1.7542, -0.402 ,  0.1276],
       [ 1.0963, -0.7157, -0.8886,  0.202 ,  0.0959],
       [-0.7661,  0.3306,  0.8688, -0.2072,  0.6752],
       [ 0.9134, -0.1997, -1.266 , -0.0604, -0.9468]])

#### Forward + backward pass

In [323]:
@njit
def solve(A, B):
    L, R = cholesky_decompose(A)
    C = solve_fwd(L, B)
    X = solve_back(C, L, R)
    return X

In [324]:
X_out = solve(S, B)
X_out

array([[ 0.3687,  3.6485,  2.9531, -1.7842, -3.9627],
       [-1.3636,  1.6662,  2.4564, -0.6197,  0.0223],
       [ 0.4623, -0.112 , -0.3541, -0.0861, -0.3378],
       [-0.9128,  0.2053,  1.1994,  0.219 ,  1.5058],
       [-1.0906,  0.1335,  0.5197,  0.3508,  0.3267],
       [-0.6197,  3.8872,  3.3633, -1.7039, -3.7149],
       [-2.1022,  1.0846,  1.7542, -0.402 ,  0.1276],
       [ 1.0963, -0.7157, -0.8886,  0.202 ,  0.0959],
       [-0.7661,  0.3306,  0.8688, -0.2072,  0.6752],
       [ 0.9134, -0.1997, -1.266 , -0.0604, -0.9468]])

In [325]:
X_np = np.linalg.solve(S, B)
X_np

array([[ 0.3687,  3.6485,  2.9531, -1.7842, -3.9627],
       [-1.3636,  1.6662,  2.4564, -0.6197,  0.0223],
       [ 0.4623, -0.112 , -0.3541, -0.0861, -0.3378],
       [-0.9128,  0.2053,  1.1994,  0.219 ,  1.5058],
       [-1.0906,  0.1335,  0.5197,  0.3508,  0.3267],
       [-0.6197,  3.8872,  3.3633, -1.7039, -3.7149],
       [-2.1022,  1.0846,  1.7542, -0.402 ,  0.1276],
       [ 1.0963, -0.7157, -0.8886,  0.202 ,  0.0959],
       [-0.7661,  0.3306,  0.8688, -0.2072,  0.6752],
       [ 0.9134, -0.1997, -1.266 , -0.0604, -0.9468]])

In [326]:
np.allclose(X_out, X_np)

True

## Inverting the L-matrix

In [327]:
L, R = cholesky_decompose(S)

## Inverting cholesky

In [333]:
np.linalg.inv(L)

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8525, -0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2861,  0.4019, -0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.0961,  0.1005, -0.2028, -0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.0478,  0.2573,  0.031 , -0.0849, -0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.3417,  0.2155, -0.149 ,  0.254 ,  0.2451,  0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [-0.6994, -0.7018,  0.2161,  0.1929, -0.4565, -1.3205, -1.255 ,  1.    ,  0.    ,  0.    ],
       [ 0.2885,  0.9594, -0.0221,  0.5107,  0.2212,  0.6297,  1.2396, -0.5433,  1.    ,  0.    ],
       [-0.4903, -1.1056,  0.2849, -0.7281, -0.4632, -0.7845, -0.9468,  0.4717, -0.4976,  1.    ]])

In [334]:
imask = np.zeros_like(L)
imask[1, 1] = 1.0
imask = np.eye(d)

In [337]:
solve_fwd(L, imask)

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8525, -0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2861,  0.4019, -0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.0961,  0.1005, -0.2028, -0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.0478,  0.2573,  0.031 , -0.0849, -0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.3417,  0.2155, -0.149 ,  0.254 ,  0.2451,  0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [-0.6994, -0.7018,  0.2161,  0.1929, -0.4565, -1.3205, -1.255 ,  1.    ,  0.    ,  0.    ],
       [ 0.2885,  0.9594, -0.0221,  0.5107,  0.2212,  0.6297,  1.2396, -0.5433,  1.    ,  0.    ],
       [-0.4903, -1.1056,  0.2849, -0.7281, -0.4632, -0.7845, -0.9468,  0.4717, -0.4976,  1.    ]])

In [336]:
np.linalg.solve(L, imask)

array([[ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.4195,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.8525, -0.2938,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.2861,  0.4019, -0.1168,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.0961,  0.1005, -0.2028, -0.0782,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.0478,  0.2573,  0.031 , -0.0849, -0.0513,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [-0.3417,  0.2155, -0.149 ,  0.254 ,  0.2451,  0.6293,  1.    ,  0.    ,  0.    ,  0.    ],
       [-0.6994, -0.7018,  0.2161,  0.1929, -0.4565, -1.3205, -1.255 ,  1.    ,  0.    ,  0.    ],
       [ 0.2885,  0.9594, -0.0221,  0.5107,  0.2212,  0.6297,  1.2396, -0.5433,  1.    ,  0.    ],
       [-0.4903, -1.1056,  0.2849, -0.7281, -0.4632, -0.7845, -0.9468,  0.4717, -0.4976,  1.    ]])